### ISSUE TITLE
[Question]: would it be possible to integrate werewolves with the witchery mod?

### ISSUE THREAD

**Issue by xronin01** [Rozmir-Rohi/mo-creatures-legacy#2]

**Comment by Rozmir-Rohi** [comment]
Assuming that the link below is the source code for the witchery mod, this might be possible
https://github.com/Bogdan-G/Witchery/tree/master


But I need more information. How would you like Mo'Creatures werewolves to be integrated with the Witchery mod?

**Comment by Rozmir-Rohi** [comment]
Never mind, I found out that the link to that Witchery source code repository is an illegal redistribution of the Witchery source code.

Replacing the model and texture for the Wolfman entity from the Witchery mod is possible by using mixins to overwrite registerRenderers() in ClientProxy from the Witchery mod.
However, I can't add this in because I would need permission from Emoniph to use the Witchery source code or mod jar in my repository.
The last time Emoniph was active on Curseforge was 2016 so I don't think they are coming back.

Instead, I will make it so that Mo' Creatures werewolves take extra damage when attacked with a Witchery Silver Sword.

**Comment by Rozmir-Rohi** [comment]
I found a workaround for this!

This is now on the final list of things to do.

**Comment by brandyyn** [comment]
@xronin01 oh my god is this you hahaha 
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/11356565/cb31ee33-528a-4494-b545-e1d5f9997f96)
