### ISSUE TITLE
Config options for some changes / feature requests

### ISSUE THREAD

**Issue by brandyyn** [Rozmir-Rohi/mo-creatures-legacy#34]
This is amazing work and i'm really excited to use this, i just have a few requests if they're not already in the mod.

> Snails, Maggots, and Jellyfish now no longer drop slime balls.

could this be a config option? i think it's a nice way to get slime balls in my pack.

> Fixed flying horse speed glitch when players have a creature on their head or in their hand. Now players cannot ride a horse with another creature in their hand or on their head. :(

can this be a config option? i want to ride around with a bunny on my head!

also i highly highly doubt this one, but could there be a config or a resource pack to bring back the old textures instead of the new 16x textures? is that possible? 

this may be a big ask but could you add giant pandas like in newer mc versions? :D

>  Pandas can now be tamed and healed with Biomes O' Plenty, Et Futurum Requiem, and Tropicraft Bamboo.

can you add growthcraft bamboo and maybe plantmegapack bamboo too?(although pmp might be too messy as there's so many different types of bamboo in that)

> Removed all small fish except for anchovies, goldfish, and angel fish as they were the only freshwater fish. This was done to make small fish only freshwater fish.

whatttt, that's not cool, we want more variety than just 3 fish. i loved the fish :/ surely this can be a config option for people who don't care about "realism" 

> Health bars for pets now only show if they are hurt. Health bars can still be disabled altogether through config.

can we have a config to turn this back to show health all the time like the original?

> Wraiths and Flame Wraiths can now go through walls.

this is bound to be very annoying :/ im pretty sure the twilight forest has the same thing which is not fun. could this be a config option please?

> Improved picked-up behaviour for mice, pet scorpions, snakes, birds, and bunnies. Mouse and Pet Scorpion will now get dropped from the player's hand if the player does not have an empty hand selected. All the previous creatures will also no longer take damage if you try to punch them while you have picked them up.

could this also be a config option, i understand the creatures are "too big" to be held with an item in hand but that's just no fun in my opinion :/ i'd like to carry any creature and be able to switch to any items, this just seems SO tedious

> Elephant bulldozer can now only destroy logs and leaves (anything from a tree). This was done to make elephants similar to real life where they can knock down trees.

this gets rid of a lot of functionality of the elephant bulldozer, could this also be a config option?

> All ridable creatures can now only be mounted with an empty hand.

this also seems tedious, if i have a full hotbar or inventory, i need to move or drop an item every time before mounting something? it would be good as a config option too 

> If you use this mod with the Netherlicious mod, the Mo' Creatures mobs that are supposed to spawn in the nether don't spawn there. So you will need to manually add nether spawns for Mo' Creatures nether mobs using the Just Another Spawner Mod.

is this a problem with original mo creatures? i can't use just another spawner in my pack because it crashes with one of my mods. surely this can be fixed without the need for just another spawner?

i really really like a lot of your changes and fixes, bug these are the ones i have problems with, and most should be easy to solve if you could give the project some more of your time. thank you for the project and thank you for even considering some of these <3

**Comment by Rozmir-Rohi** [comment]
**Things that will definitely be added:**
- Config option to re-add slime drops for previously slime-dropping insects

- Add Growthcraft bamboo and Plantmegapack bamboo  as panda food item

- Config option to return health bars to original Mo' Creatures

- Return elephant bulldozer to original Mo' Creatures

- Config option to return pickup behaviour to original Mo' Creatures

- Config option to control whether mounting occurs with an empty hand or not

	

**Things I will try to add:**
- Config option for 16x textures

 - Fix for Netherlicious. It's unlikely I will be able to fix this though.


**Things I won't add unless you give me a good enough reason:**
 - Re-add small fish varieties - I have readded anglerfish and mandarinfish in beta 1.2. The small fish varieties that remain removed are hippotang and clownfish, I did this because there were already the same type of fish in the fishy entity.


**Things that don't need any changes:**
- Config option for wraiths and flame wraiths for going through walls - I've removed the ability for wraiths and flame wraiths to go through walls in beta 1.2.


**Things I will not add:**
- Make pandas like in the new versions of minecraft. - I don't have enough time till the deadline to do this.

- Re-add ability to ride horses a creature picked up or on the players head - this causes mounts to be uncontrollably fast.

**Comment by brandyyn** [comment]
thank you so much!! i really appreciate you taking the time to consider and respond to my suggestions. this is really the definitive version of mo creatures for 1.7.10, thank you so damn much!

i hadn't thought of looking at the release notes actually, thanks for reminding me. 

> * Re-add small fish varieties - I have readded anglerfish and mandarinfish in beta 1.2. The small fish varieties that remain removed are hippotang and clownfish, I did this because there were already the same type of fish in the fishy entity.

if i'm interpreting this right, dory and nemo still spawn from the fish entity even though they have individually been removed?

> Fix for Netherlicious. It's unlikely I will be able to fix this though.

I'm friends with the author of Netherlicious, is there anything they can do to help? What exactly is the issue? :0 could you also confirm if this happens with the original mocreatures or only your fork? i tried to find some using netherlicious and original mo creatures and it seems like its an issue with netherlicious @DelirusCrux

> Make pandas like in the new versions of minecraft. - I don't have enough time till the deadline to do this.

My suggestion wasn't to MAKE them like the new versions of minecraft, but to add them or an equivalent so we'd have both small and giant pandas, doesn't matter though. there will be other mods that add them, or equivalents anyway, was just a suggestion that you may have liked haha

> I've removed the ability for wraiths and flame wraiths to go through walls in beta 1.2.

it would be cool if this is a config option 

> Re-add ability to ride horses a creature picked up or on the players head - this causes mounts to be uncontrollably fast.

not a huge loss, i had never encountered this issue and it doesnt seem to happen to me? tested with normal mc horse and wildhorse from mo creatures

![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/11356565/e0da9c77-2050-4ea9-91ae-ae3bbe9d65e1)
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/11356565/59249d71-5f2f-4910-af36-56886f04db85)

**Comment by Rozmir-Rohi** [comment]
Updated the to do list, see above.
<br>

- Hippotang (Dory), and Clownfish (Nemo) varieties spawn as only as Fishy entity variants in Mo' Creatures Legacy, not as Small Fish entity variants.

Fishy entity Hippotang variant with original Mo' Creatures texture:
https://static.wikia.nocookie.net/mocreatures_gamepedia_en/images/9/96/Fishy1.png/revision/latest?cb=20230708123721

Fishy entity Clownfish variety with original Mo' Creatures texture:
https://static.wikia.nocookie.net/mocreatures_gamepedia_en/images/1/12/Fishy2.png/revision/latest?cb=20230708123728

<br>

- Thank you for requesting the Netherlicious biome spawning issue to be fixed. By going back and looking at why the issue happens, I was able to make a fix for it.
The original Mo' Creatures mod does not provide biome spawning integration with Netherlicious, but spawns can be added for the original Mo' Creatures using Just Another Spawner.

- Just to confirm, you would like a config option for the ability of Wraiths and Flame Wraiths to  go through walls?

- The problem with mount speed when players have a creature picked up or on their head is only a problem for flying mounts, for flying mounts it causes them to fly extremely fast. If you want I can add a config option to so that players can have creatures picked up or on their head when riding a non-flying mount. But please let me know if you would like this feature.

**Comment by brandyyn** [comment]
the images you linked above are broken D:

i'm glad all the varieties of fish still spawn, also, i never said this but i'm glad you removed the ent hahaha

> Thank you for requesting the Netherlicious biome spawning issue to be fixed. By going back and looking at why the issue happens, I was able to make a fix for it.

that's awesome, good job, thanks so much!! :D

> Just to confirm, you would like a config option for the ability of Wraiths and Flame Wraiths to go through walls?

yes that would be lovely :)


> If you want I can add a config option so that players can have creatures picked up or on their head when riding a non-flying mount. But please let me know if you would like this feature.

yes that would be awesome :D 

thank you so much, you are really the best!!

**Comment by Rozmir-Rohi** [comment]
Added features with recent commit.

**Comment by brandyyn** [comment]
> Added features with recent commit.

Just looked at the the commit, thank you so damn much!! I’m so so so happy, one last minor thing if you have time but I thought it would be a good feature 

> Added config option to control pet health display modes:
	0 = Do not show health bar for pets
	1 = Always show health bar for pets
	2 = Only show health bar for pets if they are hurt

what if there’s a third mode where it only shows pets health if you look at them?

No worries if you’re done with the mod now. I’m so proud of you, thank you so much for taking the time to add all of these features for me<3

**Comment by Rozmir-Rohi** [comment]
Sorry I won't be adding a third mode for the pet health display.
It is too complicated to add in the time remaining.

**Comment by brandyyn** [comment]
> Sorry I won't be adding a third mode (only show pet health if you look at them) for the pet health display. It is too complicated to add in the time remaining.

no problem, thanks a million for everything <3
