### ISSUE TITLE
[Other Mod's Issue] Immersive Engineering v0.7.8 Crashes Minecraft on Start Up

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#52]
[crash-2024-03-08_18.32.04-client.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14537018/crash-2024-03-08_18.32.04-client.txt)
[crash-2024-03-08_18.32.02-client.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14537019/crash-2024-03-08_18.32.02-client.txt)

**Comment by Rozmir-Rohi** [comment]
Could you please confirm that Mo' Creatures Legacy is causing the issue?

From reading the crash report I think this crash has something to do with the Witchery mod or the Witchery mod's interaction with either the Immersive Engineering mod or another mod.

If this is caused by Mo' Creatures Legacy please explain when this crash happens (eg: happens when launching Minecraft or happens because of something in-game). If the issue happens because of something in-game please explain what it is.

**Comment by Omgise** [comment]
When I tried the Immersive Engineering mod and the Mo 'Creatures Legacy mod, the game crashed and I'm pretty sure it was the Mo 'Creatures Legacy.
![image](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/106000018/4e055f4c-742c-4af9-a33e-d2555fcd6808)
[crash-2024-03-09_16.12.10-client.txt](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14545636/crash-2024-03-09_16.12.10-client.txt)
[fml-client-latest.log](https://github.com/Rozmir-Rohi/mo-creatures-legacy/files/14545637/fml-client-latest.log)

**Comment by Rozmir-Rohi** [comment]
I think it might be Immersive Engineering v0.7.8 that is causing the issue, the crash report says that the game crashed because Minecraft could not find the following files:
- blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.class
- cofh/api/energy/IEnergyHandler.class
<br>
I'm able to launch Minecraft with Immersive Engineering v0.7.7 and Mo' Creatures Legacy Final-1.1 without the game crashing.

![im eng and moc legacy](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/41c663d5-56f9-4a8f-8cdc-a6219f6a3f09)

**Comment by Omgise** [comment]
Yes, I found that Immersive Engineering v0.7.8 is the problem, and v0.7.7 doesn't crash the game.
