### ISSUE TITLE
Please add ore dictionary tags for most items

### ISSUE THREAD

**Issue by 167OSS** [Rozmir-Rohi/mo-creatures-legacy#55]

**Comment by Rozmir-Rohi** [comment]
I've added vanilla ore dictionary tags for the wyvern lair log, stone, planks and leaves. But I'm not sure if there's any other item that I can add vanilla ore dictionary tags for, because they don't seem to fit into any of the categories (see below).


<details>
<summary>Vanilla Ore Dictionaries</summary>

logWood

plankWood

slabWood

stairWood

stickWood

treeSapling

treeLeaves

oreGold

oreIron

oreLapis

oreDiamond

oreRedstone

oreEmerald

oreQuartz

oreCoal

blockGold

blockIron

blockLapis

blockDiamond

blockRedstone

blockEmerald

blockQuartz

blockCoal

blockGlass

paneGlassColorless

paneGlass

ingotIron

ingotGold

ingotBrick

ingotBrickNether

nuggetGold

gemDiamond

gemEmerald

gemQuartz

dustRedstone

dustGlowstone

gemLapis

slimeball

glowstone

cropWheat

cropPotato

cropCarrot

stone

cobblestone

sandstone

sand

dye

record

</details>



What other items would you like added with ore dictionary tags?
Or would you like me to give MoC items ore dictionary tags that are from other mods? If so, from which mods?

**Comment by 167OSS** [comment]
I think the ore dictionary support in this fork is fine, maybe you can refer to it.
https://github.com/jss2a98aj/mocreaturesdev/releases

Could you add compatibility support for the following mods?Many people in our Chinese Minecraft 1.7.10 modded Community love to play these mods.Sorry for the trouble.
Feed for pandas:
BambooMod:itembamboo https://web.archive.org/web/20181208064420/http://forum.minecraftuser.jp/viewtopic.php?f=13&t=172
etfuturum:bamboo https://github.com/Roadhog360/Et-Futurum-Requiem
Wa:take https://web.archive.org/web/20181116004922/http://forum.minecraftuser.jp/viewtopic.php?t=13857
(Or use the oredict ore:bamboo, ore:cropBamboo, and ore:cropBambooshoot for this compatibility)

horse meat drop:LotsOfFood:chevalcru The links is broken :(
Suggested use of ore:cropCoconut for feeding elephants.
Suggested use of ore:cropKelp and cropSeaweed for feeding fish.
rabbit drop if etfuturum is installed:etfuturum:rabbit_raw etfuturum:rabbit_hide etfuturum:rabbit_foot
Goat drops if Novacraft is installed:nova_craft:raw_chevon https://modrinth.com/mod/novacraft
Added more weakness items for Werewolf: All gold weapons from balkons-weaponmod-legacy https://www.curseforge.com/minecraft/mc-mods/balkons-weaponmod-legacy
Gold scythe from thermal foundation, silver sword, electrum sword (for which maybe consider double damage?). Because its recipe is made from silver and gold dust)

**Comment by Rozmir-Rohi** [comment]
Added features with recent commit.

### Overview:
**Panda Feeding Items:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added Items from *Universal Bamboo* Mod:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BambooMod:itembamboo

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Et Futurum Requiem:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(etfuturum:bamboo is already supported)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added Ore Dictionaries from *Wa (Japanese Style Mod)*:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ore:bamboo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ore:cropBamboo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ore:cropBambooshoot


**Horse Drops:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added Items from *Lots Of Food* mod:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Horse Dies Normally: LotsOfFood:chevalcru
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Horse Dies Burning: LotsOfFood:chevalcuit


**Elephant Feeding Items:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added Ore Dictionary: ore:cropCoconut


**Feeding Items for SmallFish and Fishy Entities that Live in Salt Water:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ore:cropKelp was already supported)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added: ore:cropSeaweed


**Bunny Drops:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added Items from *Et Futurum Requiem* mod:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Bunny Dies Normally: etfuturum:rabbit_raw   and/or etfuturum:rabbit_hide  and/or etfuturum:rabbit_foot
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Bunny Dies Burning: etfuturum:rabbit_cooked


**Goat Drops:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Added Items from *Nova Craft* mod:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Goat Dies Normally: nova_craft:raw_chevon
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If Bunny Dies Burning: nova_craft:cooked_chevon
