### ISSUE TITLE
Crash when looking at Medium Fish that doesn't have a pet name

### ISSUE THREAD

**Issue by Omgise** [Rozmir-Rohi/mo-creatures-legacy#60]
[crash-2024-12-15_20.30.37-client.txt](https://github.com/user-attachments/files/18140388/crash-2024-12-15_20.30.37-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/18140390/fml-client-latest.log)

**Comment by Rozmir-Rohi** [comment]
I think this bug happens when the player tries to look at a naturally spawned untamed Medium Fish that doesn't have a name and for some reason, the Medium Fish tries to render it's name tag when it doesn't actually have a name.

I was experiencing this same bug a few days ago, but I can't seem to replicate it on the development version since yesterday. So I think that either this bug is elusive, or I might have unknowingly fixed this with the changes I made in the past days.

I've released a snapshot version now, so if you can still replicate this bug on the snapshot version, I'll continue investigating it. Please let me know you find.

**Comment by Omgise** [comment]
Thank you. I'll look at it over the weekend

**Comment by Omgise** [comment]
Thank you. I'm glad to hear that it has been fixed.

**Comment by Omgise** [comment]
Yes, it has been fixed. Thank you.
